### DISCUSSION TITLE
Set HTTP/2 as default

### DISCUSSION THREAD

**Discussion by sanchay9** [mistweaverco/kulala-fmt#31] [Q&A] [answered]
how can I set HTTP/2 as default instead of HTTP/1.1 on format

**Comment by gorillamoe** [comment]
There is currently now way of forcing the formatter to default to this, instead of 1.1.

But it's a nice addition. Can you open a Feature Request Issue. I can then start implementing a `.kulala-fmt.yaml` where you can define such things on a project or root level.

**Comment by gorillamoe** [comment, marked as answer]
Is configurable via a `kulala-fmt.yaml` configuration file now.

```yaml
# yaml-language-server: $schema=https://fmt.getkulala.net/schema.json
---
defaults:
  http_method: GET
  http_version: HTTP/2.0
```

**Comment by sanchay9** [comment]
thanks a lot! 

that also makes it possible to not show the HTTP/x on format like this:
```yaml
defaults:
  http_method: GET
  http_version: ""
```
